# Generated by Django 5.1.4 on 2024-12-05 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('tiered', 'Tiered Discount')], max_length=20)),
                ('priority', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('fixed_amount', models.FloatField(blank=True, null=True)),
                ('tier_criteria', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.FloatField()),
                ('product_type', models.CharField(choices=[('seasonal', 'Seasonal Product'), ('bulk', 'Bulk Product'), ('premium', 'Premium Product')], max_length=20)),
                ('season_discount', models.FloatField(blank=True, null=True)),
                ('tiered_discounts', models.JSONField(blank=True, null=True)),
                ('markup_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TieredDiscount',
            fields=[
                ('discount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pricing.discount')),
            ],
            bases=('pricing.discount',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0)),
                ('discounts', models.ManyToManyField(to='pricing.discount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='pricing.OrderProduct', to='pricing.product'),
        ),
    ]
